config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :tasks
  get 'new_task', to: 'tasks#new'
  post 'create_task', to: 'tasks#create'
  get 'edit_task/:id', to: 'tasks#edit'
  patch 'update_task/:id', to: 'tasks#update'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  def index
    @tasks = Task.all
  end

  def show
    @task = Task.find(params[:id])
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    if @task.save
      redirect_to tasks_path
    else
      render :new
    end
  end

  def edit
    @task = Task.find(params[:id])
  end

  def update
    @task = Task.find(params[:id])
    if @task.update(task_params)
      redirect_to tasks_path
    else
      render :edit
    end
  end

  def destroy
    @task = Task.find(params[:id])
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<%= form_with(model: @task, url: task_path(@task), method: :patch) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>
  <%= form.submit 'Update Task' %>
<% end %>

app/views/tasks/index.html.erb
<h1>TODO</h1>
<ul>
  <% @tasks.each do |task| %>
    <li>
      <%= check_box_tag "task_#{task.id}", 1, task.completed %>
      <%= link_to task.title, task_path(task) %>
      <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure?' } %></li>
  <% end %>
</ul>

app/views/tasks/new.html.erb
<h1>Add New Task</h1>
<%= form_with(model: @task, url: create_task_path) do |form| %>
  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, required: true %>
  </div>

  <div class="field">
    <%= form.label :details %>
    <%= form.text_area :details %>
  </div>

  <div class="field">
    <%= form.label :completed %>
    <%= form.check_box :completed %>
  </div>
  <%= form.submit 'Create Task' %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task Details</h1>
<p><strong>Title:</strong> <%= @task.title %></p>
<p><strong>Details:</strong> <%= @task.details %></p>
<p><strong>Completed:</strong> <%= check_box_tag "completed", 1, @task.completed, disabled: true %></p>
<%= link_to 'Edit', edit_task_path(@task) %> |
<%= link_to 'Back', tasks_path %>